version: '3'

services:
  node:
    image: node:latest
    working_dir: /home/nodejs/app
    container_name: kml-scraper-node
    volumes:
       - .:/home/nodejs/app
    command: ["tail", "-f", "/dev/null"]