version: '3'

services:
  node-service:
    image: node:latest
    working_dir: /home/nodejs/app
    container_name: kml-scraper-node
    volumes:
       - '.:/home/nodejs/app'
    tty: true
    stdin_open: true
  gdal-service:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /data
    container_name: kml-scraper-gdal
    volumes:
      - .:/data
    command: ["tail", "-f", "/dev/null"]
    tty: true
    stdin_open: true